'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,ArrowRight,BarChart3,BookOpen,Check,ChevronDown,ChevronRight,Database,FileText,Globe2,HelpCircle,LayoutDashboard,LoaderCircle,Search,ShieldCheck,TrendingUp,Wallet,Activity,RefreshCw} from 'lucide-react';
import {Area,AreaChart,Bar,CartesianGrid,ComposedChart,Line,Tooltip,XAxis,YAxis} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarProvider,SidebarTrigger,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import snapshots from '@/data/companies.json';
import type {Company,Period} from '@/lib/sec/normalize';
const companies=[['AAPL','Apple','苹果'],['MSFT','Microsoft','微软'],['NVDA','NVIDIA','英伟达'],['GOOGL','Alphabet','谷歌'],['AMZN','Amazon','亚马逊'],['TSLA','Tesla','特斯拉']];
const names:Record<string,string>={AAPL:'苹果公司',MSFT:'微软公司',NVDA:'英伟达',GOOGL:'Alphabet',AMZN:'亚马逊',TSLA:'特斯拉'};
const amount=(v:number|null|undefined)=>v==null?'—':Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:`$${(v/1e6).toFixed(1)}M`;
const percent=(v:number|null|undefined)=>v==null?'—':`${v.toFixed(1)}%`;
const growth=(a:number|null|undefined,b:number|null|undefined)=>a!=null&&b!=null&&b!==0?(a-b)/Math.abs(b)*100:null;
const metricConfig={revenue:{label:'营业收入',color:'#168368'},income:{label:'净利润',color:'#a7d8c6'},cashflow:{label:'经营现金流',color:'#168368'},margin:{label:'净利率',color:'#e8a84c'}};
export default function Home(){
 const [company,setCompany]=useState<Company|null>((snapshots as unknown as Record<string,Company>).AAPL??null);
 const [pendingSymbol,setPendingSymbol]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [view,setView]=useState('overview');const [period,setPeriod]=useState('annual');const [years,setYears]=useState('5');const [form,setForm]=useState('all');const [filter,setFilter]=useState('');const [metric,setMetric]=useState('revenue');const [exported,setExported]=useState(false);const controller=useRef<AbortController|null>(null);const searchRef=useRef<HTMLInputElement>(null);
 async function load(symbol:string){
  const s=symbol.trim().toUpperCase();if(!s)return;controller.current?.abort();const control=new AbortController();controller.current=control;setLoading(true);setPendingSymbol(s);setError('');
  try{const r=await fetch(`/api/company?ticker=${encodeURIComponent(s)}`,{signal:AbortSignal.any([control.signal,AbortSignal.timeout(45000)])});const d=await r.json() as Company & {error?:string};if(!r.ok)throw new Error(d.error);if(control.signal.aborted)return {ok:false,error:'请求已取消'};setCompany(d);setQuery(d.ticker);setForm('all');setFilter('');return {ok:true,ticker:d.ticker,source:d.source};}
  catch(e){const message=e instanceof DOMException&&e.name==='TimeoutError'?`${s} 加载超时，请重试。`:e instanceof Error?e.message:'加载失败，请重试。';if(!control.signal.aborted)setError(message);return {ok:false,error:message};}finally{if(!control.signal.aborted)setLoading(false);}
 }
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',listener);return()=>{window.removeEventListener('keydown',listener);controller.current?.abort();};},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'search_sec_company',description:'Search a stock ticker or CIK and display its SEC financial analysis.',inputSchema:{type:'object',properties:{ticker:{type:'string'}},required:['ticker'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input.ticker!=='string'||!/^(?:[A-Za-z][A-Za-z0-9.-]{0,9}|\d{1,10})$/.test(input.ticker))throw new Error('Invalid ticker');const result=await load(input.ticker);if(!result?.ok)throw new Error(result?.error||'Search failed');return result;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const allPeriods=company?.[period==='annual'?'annual':'quarterly']??[];const data=allPeriods.slice(-Number(years));const latest=allPeriods.at(-1);const previous=latest?allPeriods.find(p=>{const delta=(Date.parse(latest.end)-Date.parse(p.end))/86400000;return delta>=350&&delta<=380;}):undefined;const margin=latest?.income!=null&&latest.revenue?latest.income/latest.revenue*100:null;
 const graph=data.map(p=>({...p,revenue:p.revenue==null?null:p.revenue/1e9,income:p.income==null?null:p.income/1e9,cashflow:p.cashflow==null?null:p.cashflow/1e9,margin:p.income!=null&&p.revenue?p.income/p.revenue*100:null}));
 const visibleFilings=(company?.filings??[]).filter(f=>(form==='all'||f.form===form)&&`${f.form} ${f.title} ${f.date}`.toLowerCase().includes(filter.toLowerCase()));
 function exportCSV(){if(!company)return;const rows=[['company','period','start','end','revenue_usd','net_income_usd','operating_cashflow_usd','revenue_source_accession'],...data.map(p=>[company.ticker,p.label,p.start,p.end,p.revenue,p.income,p.cashflow,p.source])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${company.ticker}-SEC-${period}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExported(true);setTimeout(()=>setExported(false),2000);}
 const nav=[['overview','财务概览',LayoutDashboard],['financials','财务报表',BarChart3],['filings','SEC 申报文件',FileText]] as const;
 return <SidebarProvider style={{'--sidebar-width':'230px'} as React.CSSProperties}>
  <Sidebar className="research-sidebar"><SidebarHeader className="brand"><div className="brand-mark"><BarChart3 size={23}/></div><div>SEC<span>Insight</span><small>上市公司研究工作台</small></div></SidebarHeader><SidebarContent><div className="nav-caption">研究空间</div><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton onClick={()=>setView(id)} isActive={view===id} className="nav-item"><Icon/><span>{label}</span>{view===id&&<ChevronRight size={15}/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-caption company-caption">快捷公司 <span>06</span></div><div className="company-list">{companies.map(([ticker,name,cn],i)=><button className={`company-link ${company?.ticker===ticker?'selected':''}`} key={ticker} onClick={()=>load(ticker)} disabled={loading}><span className={`mini-logo logo-${i}`}>{ticker==='AAPL'?'a':name[0]}</span><span><b>{ticker}</b><small>{cn}</small></span>{company?.ticker===ticker&&<span className="selected-dot"/>}</button>)}</div><div className="source-note"><ShieldCheck size={20}/><b>从一手披露开始</b><p>财务数据来自 SEC EDGAR，<br/>每一份申报都可追溯。</p><a href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces" target="_blank" rel="noreferrer">了解数据来源 <ArrowUpRight size={14}/></a></div></SidebarContent><SidebarFooter><button className="method-link" onClick={()=>setView('methodology')}><BookOpen size={17}/>数据与计算口径<ArrowUpRight size={15}/></button><div className="sidebar-bottom"><span className="avatar">研</span><div>个人研究空间<small>SEC Insight Workspace</small></div></div></SidebarFooter></Sidebar>
  <div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-toggle"/><span>研究空间</span><ChevronRight size={14}/><strong>{view==='methodology'?'数据与计算口径':nav.find(n=>n[0]===view)?.[1]}</strong></div><form className="global-search" onSubmit={e=>{e.preventDefault();load(query);}}><Search size={17}/><Input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索股票代码或 CIK，如 AAPL" aria-label="搜索股票代码或 CIK"/><button aria-label="提交搜索" type="submit" disabled={loading}>{loading?<LoaderCircle size={17} className="spin"/>:<span>搜索</span>}</button></form><a className="sec-top" href="https://www.sec.gov/edgar/search/" target="_blank" rel="noreferrer"><Globe2 size={16}/> SEC EDGAR <ArrowUpRight size={13}/></a></header>
  <main className="main-content" aria-busy={loading}><div className="page-heading"><div className="eyebrow">COMPANY INTELLIGENCE</div><div className="heading-row"><h1>{view==='overview'?'财务概览':view==='financials'?'财务报表':view==='filings'?'SEC 申报文件':'数据与计算口径'}</h1><span className="heading-note">用公开披露，理解企业。</span></div></div>
  {loading&&<div className="loading-banner" role="status"><LoaderCircle className="spin" size={17}/><span>正在加载 <strong>{pendingSymbol}</strong> 的 SEC 财报…{company&&` 当前仍展示 ${company.ticker}，完成后自动切换。`}</span></div>}
  {error&&<div role="alert" className="error-banner"><span>{error}{company&&` 当前仍展示 ${company.ticker}。`}</span><button onClick={()=>load(pendingSymbol||query)}>重试</button><button onClick={()=>setError('')}>关闭</button></div>}
  {company&&<><section className="company-header"><div className="company-identity"><div className="main-logo">{company.ticker==='AAPL'?'a':company.ticker[0]}</div><div><div className="company-title"><h2>{names[company.ticker]||company.name}</h2><span className="ticker-badge">{company.exchange}: {company.ticker}</span></div><p>{company.name} <span>·</span> CIK {company.cik}</p></div></div><div className="company-actions"><Button variant="outline" onClick={()=>load(company.ticker)} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/>{loading?'同步中':'刷新数据'}</Button><Button className="export-button" onClick={exportCSV} disabled={loading}>{exported?<Check size={15}/>:<ArrowDownToLine size={15}/>} {exported?'已导出':'导出数据'}</Button></div></section>
  <div className="data-status"><span><Database size={14}/>{company.source==='snapshot'?'SEC 官方数据快照':'SEC 官方数据 · 已同步'}<span className="status-divider">|</span>采集于 {new Date(company.fetchedAt).toLocaleDateString('zh-CN')}</span><span>财年结束日以公司披露为准<HelpCircle size={13}/></span></div>
  {company.lookupSource==='cached-directory'&&<p className="lookup-note">股票代码通过历史目录缓存解析，已与 SEC 当前公司信息核对；财务数据来自 SEC。</p>}
  {company.warning&&<p className="lookup-note" role="status">{company.warning}</p>}
  <Tabs value={view} onValueChange={setView} className="main-tabs"><TabsList variant="line">{nav.map(([id,label])=><TabsTrigger value={id} key={id}>{label}</TabsTrigger>)}<TabsTrigger value="methodology">数据口径</TabsTrigger></TabsList></Tabs>
  {view==='overview'||view==='financials'?<><div className="section-heading"><div><h3>经营表现</h3><span>{latest?.label??'暂无期间'} <span className="subtle">· 截至 {latest?.end??'—'}</span></span></div><Tabs value={period} onValueChange={setPeriod}><TabsList><TabsTrigger value="annual">年度</TabsTrigger><TabsTrigger value="quarterly">季度</TabsTrigger></TabsList></Tabs></div>
  <div className="metrics">{[{label:'营业收入',key:'revenue',icon:Wallet,value:latest?.revenue,change:growth(latest?.revenue,previous?.revenue)},{label:'净利润',key:'income',icon:TrendingUp,value:latest?.income,change:growth(latest?.income,previous?.income)},{label:'净利率',key:'margin',icon:Activity,value:margin,change:null},{label:'经营现金流',key:'cashflow',icon:BarChart3,value:latest?.cashflow,change:growth(latest?.cashflow,previous?.cashflow)}].map(m=><button key={m.key} className={`metric-card ${metric===m.key?'metric-active':''}`} onClick={()=>setMetric(m.key)}><div className="metric-label">{m.label}<m.icon size={17}/></div><div className="metric-value">{m.key==='margin'?percent(m.value):amount(m.value)}</div><div className="metric-bottom">{m.change!=null?<><span className={m.change>=0?'positive':'negative'}>{m.change>=0?'↗':'↘'} {Math.abs(m.change).toFixed(2)}%</span><span>同比</span></>:<span>{m.key==='margin'?'净利润 / 营业收入':'无可比同期数据'}</span>}<svg viewBox="0 0 90 26" className="sparkline" aria-hidden="true"><path d={(()=>{const vals=allPeriods.slice(-7).map(p=>m.key==='margin'?(p.income!=null&&p.revenue?p.income/p.revenue*100:null):p[m.key as keyof Period] as number|null).filter((v):v is number=>typeof v==='number');if(vals.length<2)return '';const min=Math.min(...vals),range=Math.max(...vals)-min||1;return vals.map((v,i)=>`${i?'L':'M'}${i*88/(vals.length-1)},${24-(v-min)/range*21}`).join(' ');})()}/></svg></div></button>)}</div>
  <div className="charts-grid"><section className="panel trend-panel"><div className="panel-head"><div><h3>{metric==='margin'?'净利率趋势':metric==='cashflow'?'经营现金流趋势':'营收与利润趋势'}</h3><p>{metric==='margin'?'单位：%':'单位：十亿美元（USD billions）'}</p></div><NativeSelect aria-label="显示期间数量" value={years} onChange={e=>setYears(e.target.value)}><NativeSelectOption value="5">近 5 期</NativeSelectOption><NativeSelectOption value="8">近 8 期</NativeSelectOption></NativeSelect></div><div className="chart-legend"><span><i/>{metric==='margin'?'净利率':metric==='cashflow'?'经营现金流':'营业收入'}</span>{!['margin','cashflow'].includes(metric)&&<span><i className="light"/>净利润</span>}</div>{graph.length?<ChartContainer config={metricConfig} className="trend-chart"><ComposedChart data={graph} margin={{top:15,right:12,bottom:4,left:0}}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="label" axisLine={false} tickLine={false} tickMargin={15} fontSize={12}/><YAxis axisLine={false} tickLine={false} tickMargin={8} width={44} fontSize={12}/><Tooltip contentStyle={{borderRadius:10,border:'1px solid #e1e8e4',fontSize:13}} formatter={(value:any,name:any)=>[value==null?'—':`${Number(value).toFixed(2)}${metric==='margin'?'%':'B'}`,metricConfig[name as keyof typeof metricConfig]?.label??name]}/>{metric==='margin'?<Line dataKey="margin" type="monotone" stroke="#168368" strokeWidth={3} dot={{r:4}}/>:metric==='cashflow'?<Bar dataKey="cashflow" fill="#168368" radius={[5,5,0,0]} maxBarSize={48}/>:<><Bar dataKey="revenue" fill="#168368" radius={[4,4,0,0]} maxBarSize={33}/><Bar dataKey="income" fill="#a7d8c6" radius={[4,4,0,0]} maxBarSize={33}/></>}</ComposedChart></ChartContainer>:<div className="empty">未找到可比的标准财务数据。</div>}<div className="chart-foot"><ShieldCheck size={13}/>来源：SEC XBRL · {period==='annual'?'年度申报':'季度数据（部分由累计值差分）'}<button onClick={()=>setView('financials')}>查看明细<ArrowRight size={14}/></button></div></section>
  <section className="panel quality-panel"><div className="panel-head"><div><h3>盈利与现金质量</h3><p>{latest?.label} · 核心财务比率</p></div><TrendingUp size={19}/></div><div className="margin-feature"><span>净利率</span><strong>{percent(margin)}</strong><span className="feature-sub">每 $100 收入创造 {margin==null?'—':`$${margin.toFixed(1)}`} 净利润</span></div><div className="ratio-list">{[{label:'营业利润率',value:latest?.operating!=null&&latest?.revenue?latest.operating/latest.revenue*100:null},{label:'经营现金流 / 营收',value:latest?.cashflow!=null&&latest?.revenue?latest.cashflow/latest.revenue*100:null},{label:'资产负债率',value:latest?.liabilities!=null&&latest?.assets?latest.liabilities/latest.assets*100:null}].map((r,i)=><div className="ratio" key={r.label}><div><span>{r.label}</span><b>{percent(r.value)}</b></div><div className="ratio-track"><div style={{width:`${Math.min(100,Math.max(0,r.value??0))}%`,background:['#158168','#6cb59c','#b2c8be'][i]}}/></div></div>)}</div><div className="ratio-note"><BookOpen size={14}/>比率用于理解财务结构，不构成投资评级。</div></section></div>
  {view==='financials'&&<section className="panel financial-table"><div className="panel-head"><div><h3>标准化财务数据</h3><p>金额单位：美元 · 缺失披露显示为 —</p></div></div><Table><TableHeader><TableRow><TableHead>指标</TableHead>{data.map(p=><TableHead key={p.end}>{p.label}</TableHead>)}</TableRow></TableHeader><TableBody>{[['revenue','营业收入'],['income','净利润'],['operating','营业利润'],['cashflow','经营现金流'],['capex','资本支出'],['assets','总资产'],['liabilities','总负债']].map(([k,label])=><TableRow key={k}><TableCell>{label}</TableCell>{data.map(p=><TableCell key={p.end}>{amount(p[k as keyof Period] as number|null)}</TableCell>)}</TableRow>)}</TableBody></Table></section>}</>:null}
  {(view==='overview'||view==='filings')&&<section className="panel filings-panel"><div className="panel-head"><div className="filing-title"><h3>{view==='overview'?'最近申报':'申报文件库'}</h3><span className="count-badge">{visibleFilings.length}</span><p>直达 SEC 原始披露</p></div>{view==='overview'?<button className="text-button" onClick={()=>setView('filings')}>全部文件<ArrowRight size={15}/></button>:<div className="filing-filters"><Input placeholder="搜索类型、标题或日期" aria-label="搜索申报文件" value={filter} onChange={e=>setFilter(e.target.value)}/><NativeSelect value={form} onChange={e=>setForm(e.target.value)} aria-label="申报类型筛选"><NativeSelectOption value="all">全部类型</NativeSelectOption>{[...new Set(company.filings.map(f=>f.form))].sort().map(f=><NativeSelectOption key={f} value={f}>{f}</NativeSelectOption>)}</NativeSelect></div>}</div><Table><TableHeader><TableRow><TableHead>文件类型</TableHead><TableHead>申报文件</TableHead><TableHead>报告期</TableHead><TableHead>提交日期</TableHead><TableHead className="right">原始文件</TableHead></TableRow></TableHeader><TableBody>{visibleFilings.slice(0,view==='overview'?4:120).map(f=><TableRow key={f.accession}><TableCell><span className={`form-badge ${f.form==='10-K'?'annual-form':''}`}>{f.form}</span></TableCell><TableCell><a className="filing-name" href={f.url} target="_blank" rel="noreferrer"><FileText size={16}/>{f.form==='10-K'?'年度报告':f.form==='10-Q'?'季度报告':f.form==='8-K'?'重大事项报告':f.form==='4'?'内部人士交易披露':f.title}</a></TableCell><TableCell className="muted">{f.reportDate||'—'}</TableCell><TableCell className="muted">{f.date}</TableCell><TableCell className="right"><a className="open-filing" href={f.url} target="_blank" rel="noreferrer" aria-label={`打开 ${f.date} 的 ${f.form} 原始文件`}>查看<ArrowUpRight size={14}/></a></TableCell></TableRow>)}</TableBody></Table>{!visibleFilings.length&&<div className="empty">没有符合条件的申报文件，请调整筛选条件。</div>}<div className="table-foot">展示最近 {view==='overview'?Math.min(4,visibleFilings.length):visibleFilings.length} 份文件 · 文件库最多保留最近 120 份申报</div></section>}
  {view==='methodology'&&<section className="panel methodology"><h3>让每个数字都有出处</h3><p>股票代码优先通过 SEC 在线目录解析；目录受限时使用 sec-cik-mapper 的历史缓存，并与 SEC 当前公司信息核对代码。新上市或更名公司可能需要输入 CIK。本站读取 SEC EDGAR 的 Company Facts 和 Submissions 接口，展示公开的 XBRL 财务事实与申报目录。数据采集时间显示在公司名称下方；“快照”表示已保存的数据，不代表实时同步。</p><h4>财务期间与可比性</h4><p>年度数据选择约 330–380 天的报告期；季度选择约 70–110 天的独立报告期，必要时使用相同起始日的累计金额相减得到单季。季度标签使用实际结束年月，避免不同公司的财年编号造成误读。每股收益不可直接相减，不推导缺失季度 EPS。</p><h4>计算方法</h4><p>同比 =（本期 − 去年同期）÷ 去年同期绝对值。净利率 = 净利润 ÷ 营业收入。资产负债率 = 总负债 ÷ 总资产。不同财务事实按起止日期匹配，同一期间使用较晚披露值；重述可能改变历史数字。</p><h4>覆盖范围</h4><p>优先匹配常见 US GAAP 标签。自定义标签、IFRS 与金融行业特有指标可能缺失；缺失值显示为 —，不会替换为 0。最近申报目录包含最多 120 份文件，不等于完整历史。数据仅用于研究，不包含实时股价或投资建议。</p><a href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces" target="_blank" rel="noreferrer">阅读 SEC 官方 API 文档 <ArrowUpRight size={15}/></a></section>}
  <footer className="footer"><span><ShieldCheck size={14}/> 数据来源 SEC EDGAR</span><span>公开披露 · 独立研究 <span className="footer-dot">·</span> {company.ticker}</span></footer></>}
  {!company&&<div className="empty panel">输入美股代码，开始查看 SEC 财务披露。</div>}
  </main></div>
 </SidebarProvider>;
}
